const nodemailer = require("nodemailer");

/**
 * Creates a Nodemailer transporter from environment variables.
 * Supports any SMTP provider (Gmail, Resend SMTP, Mailgun, etc.)
 */
const createTransporter = () =>
  nodemailer.createTransport({
    host: process.env.SMTP_HOST,
    port: parseInt(process.env.SMTP_PORT || "587", 10),
    secure: process.env.SMTP_SECURE === "true", // true for 465, false for other
    auth: {
      user: process.env.SMTP_USER,
      pass: process.env.SMTP_PASS,
    },
  });

/**
 * Sends the AI-generated sales summary to the specified recipient.
 *
 * @param {string} to - Recipient email address
 * @param {string} summaryMarkdown - Markdown-formatted AI summary
 * @param {string} filename - Original uploaded filename (for context)
 */
const sendSummaryEmail = async (to, summaryMarkdown, filename) => {
  const transporter = createTransporter();

  // Convert basic markdown bold/headers to simple HTML for email clients
  const htmlBody = summaryMarkdown
    .replace(/^## (.+)$/gm, "<h2>$1</h2>")
    .replace(/^### (.+)$/gm, "<h3>$1</h3>")
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    .replace(/\n/g, "<br>");

  const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <style>
    body { font-family: Georgia, serif; background: #fafafa; padding: 32px; color: #1a1a1a; }
    .card { background: #fff; border: 1px solid #e0e0e0; border-radius: 8px; padding: 32px; max-width: 680px; margin: 0 auto; }
    h1 { font-size: 22px; color: #0f0f0f; border-bottom: 2px solid #f59e0b; padding-bottom: 12px; }
    h2 { font-size: 17px; color: #1a1a1a; margin-top: 24px; }
    h3 { font-size: 15px; color: #374151; }
    p, li { line-height: 1.7; color: #374151; }
    .footer { margin-top: 32px; font-size: 12px; color: #9ca3af; border-top: 1px solid #f0f0f0; padding-top: 16px; }
    .badge { display: inline-block; background: #fef3c7; color: #92400e; padding: 2px 8px; border-radius: 4px; font-size: 12px; font-weight: bold; }
  </style>
</head>
<body>
  <div class="card">
    <h1>📊 Sales Intelligence Briefing</h1>
    <p><span class="badge">AI GENERATED</span> &nbsp; Source file: <strong>${filename}</strong></p>
    <hr style="border:none;border-top:1px solid #f0f0f0;margin:20px 0"/>
    ${htmlBody}
    <div class="footer">
      Generated by Sales Insight Automator · Powered by Groq Llama 3 · ${new Date().toUTCString()}
    </div>
  </div>
</body>
</html>`;

  const info = await transporter.sendMail({
    from: `"Sales Insight Bot" <${process.env.SMTP_USER}>`,
    to,
    subject: `📊 Sales Intelligence Briefing — ${filename}`,
    text: summaryMarkdown, // plain-text fallback
    html,
  });

  return info.messageId;
};

module.exports = { sendSummaryEmail };
